include:
  - project: "infrastructure/gitlab-ci"
    ref: main
    file: "/templates/cloudbuild-common.gitlab-ci.yaml"

stages:
  - cloudbuild

cloudbuild:package:
  extends: .cloudbuild:deb-package-nodekeeper
  only:
    - tags
  except:
    - branches
  variables:
    REPO_NAME: broxus-deb-pub
